# Generated by Django 3.2.13 on 2023-01-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_app', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ServiceRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.servicerequest'),
        ),
    ]
