# Generated by Django 3.2.13 on 2023-02-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computoregistrado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='computoregistrado',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computoregistrado',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.area'),
        ),
        migrations.AlterField(
            model_name='computoregistrado',
            name='date_registed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.area'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='ComputoRegistrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.computoregistrado'),
        ),
    ]
